### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by acw0** [acw0/fileghost#1]
- [ ] Move configuration to a file.

Currently, the software supports a single configuration option (authentication) - which can be set via an environment variable; as more features are implemented, environment variables can get a bit cluttered. 
This can be solved by using a file for configuration - two common formats are JSON and YAML.

- [ ]  Custom storage location support

This is the most important point at the moment.
Users oftentimes do not have a lot of storage space available on their server, and may prefer to instead use a S3-compatible file storage solution.
TODO: *What other storage solutions should be implemented?*

- [ ] MIME-type parsing

While receiving the file extension as a POST header technically works, it's quite a hacky solution and really has no place in production software. Look into using [pkg/mime](https://golang.org/pkg/mime/) for server side MIME-type parsing.

- [ ] Multi-user support

For the author, software is best when it is shared. As of now, this software only works for a single user - or for any number of users acting as one single entity. There is no authentication, only authorization.
This is a relatively large task, and a separate issue may be created for it at a later date.

- [ ] Web interface

It is the year 2020 as I am writing this, and the majority of those who access the Internet do so via graphical methods. Creating a web-based interface would make this software much more accessible to those who do not prefer text input to buttons.
